Tratar dados 'tempo.csv'

Aparencia: Sol, Nublado e chuva |
Temperatura: -130 ~ 130F |
Umidade: 0 ~ 100 | 
Jogar: Sim ou Nao

Importar dados

In [1]:
import pandas as pd
import statistics as sts

In [54]:
dataset = pd.read_csv('data/tempo.csv', sep=';')
dataset.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol           85     85.0       FALSO   nao
1       sol           80     90.0  VERDADEIRO   nao
2   nublado           83     86.0       FALSO   sim
3     chuva           70      NaN       FALSO   sim
4     chuva           68     80.0       FALSO   sim

Verificar coluna Aparencia

In [55]:
#Agrupar dados e verificar a quantidade
agrupado = dataset.groupby(['Aparencia']).size()
agrupado

Aparencia
chuva      5
menos      1
nublado    3
sol        5
dtype: int64

In [56]:
#Alterar "menos" por "sol" e verificar os dados da coluna
dataset.loc[dataset['Aparencia'] == "menos", 'Aparencia'] = "sol"
agrupado = dataset.groupby(['Aparencia']).size()
agrupado

Aparencia
chuva      5
nublado    3
sol        6
dtype: int64

Verificar coluna Temperatura

In [57]:
#Verificar dados
dataset['Temperatura'].describe()

count      14.000000
mean      155.571429
std       306.433759
min        64.000000
25%        69.250000
50%        73.500000
75%        80.750000
max      1220.000000
Name: Temperatura, dtype: float64

In [58]:
#Verificar outliers
dataset.loc[(dataset['Temperatura'] < -130) | (dataset['Temperatura'] > 130)]

  Aparencia  Temperatura  Umidade  Vento Jogar
7       sol         1220     95.0  FALSO   nao

In [59]:
#Calcular mediana
mediana = sts.median(dataset['Temperatura'])
mediana

73.5

In [ ]:
#Alterar os outliers pela mediana
dataset['Temperatura'] = dataset['Temperatura'].astype(float)
dataset.loc[(dataset['Temperatura'] < -130) | (dataset['Temperatura'] > 130), 'Temperatura'] = mediana

In [64]:
#Verificar dados
dataset['Temperatura'].describe()

count    14.000000
mean     73.678571
std       6.556286
min      64.000000
25%      69.250000
50%      72.750000
75%      78.750000
max      85.000000
Name: Temperatura, dtype: float64

Verificar coluna Umidade

In [65]:
#Verificar dados
dataset['Umidade'].describe()

count     13.000000
mean      89.769231
std       34.540203
min       65.000000
25%       70.000000
50%       85.000000
75%       90.000000
max      200.000000
Name: Umidade, dtype: float64

In [66]:
#Verificar outliers
dataset.loc[(dataset['Umidade'] < 0) | (dataset['Umidade'] > 100)]

  Aparencia  Temperatura  Umidade Vento Jogar
9     chuva         75.0    200.0   NaN   sim

In [ ]:
#Verificar a existencia de NAs
dataset['Umidade'].isnull().sum()

np.int64(1)

In [ ]:
#Calcular mediana
mediana2 = sts.median(dataset['Umidade'])
mediana2

85.5

In [68]:
#Substituir outliers e NAs pela mediana
dataset.loc[(dataset['Umidade'] < 0) | (dataset['Umidade'] > 100), 'Umidade'] = mediana2
dataset['Umidade'] = dataset['Umidade'].fillna(mediana2)

In [71]:
#Verificar dados
dataset['Umidade'].describe()

count    14.000000
mean     81.285714
std       9.585073
min      65.000000
25%      71.250000
50%      85.250000
75%      89.000000
max      95.000000
Name: Umidade, dtype: float64

In [72]:
#Verificar a existencia de NAs
dataset['Umidade'].isnull().sum()

np.int64(0)

Verificar coluna Vento

In [76]:
#Agrupar dados
agrupado = dataset.groupby(['Vento']).size()
agrupado

Vento
FALSO         7
VERDADEIRO    6
dtype: int64

In [ ]:
#Verificar a existencia de NAs
dataset['Vento'].isnull().sum()

np.int64(1)

In [78]:
#Preencher o NAs com a moda (Falso)
dataset['Vento'] = dataset['Vento'].fillna("FALSO")

In [79]:
#Verificar a existencia de NAs
dataset['Vento'].isnull().sum()

np.int64(0)

Verificar coluna Jogar

In [ ]:
#Agrupar dados para validar
agrupado = dataset.groupby(['Jogar']).size()
agrupado

Jogar
nao    5
sim    9
dtype: int64

In [81]:
#Veriricar existencia de NAs
dataset['Jogar'].isnull().sum()

np.int64(0)

Tabela atualizada

In [82]:
dataset

   Aparencia  Temperatura  Umidade       Vento Jogar
0        sol         85.0     85.0       FALSO   nao
1        sol         80.0     90.0  VERDADEIRO   nao
2    nublado         83.0     86.0       FALSO   sim
3      chuva         70.0     85.5       FALSO   sim
4      chuva         68.0     80.0       FALSO   sim
5      chuva         65.0     70.0  VERDADEIRO   nao
6        sol         64.0     65.0  VERDADEIRO   sim
7        sol         73.5     95.0       FALSO   nao
8        sol         69.0     70.0       FALSO   sim
9      chuva         75.0     85.5       FALSO   sim
10       sol         75.0     70.0  VERDADEIRO   sim
11   nublado         72.0     90.0  VERDADEIRO   sim
12   nublado         81.0     75.0       FALSO   sim
13     chuva         71.0     91.0  VERDADEIRO   nao